# Type can be "random" or "fixed." Random will pick a MOTD from the list. Fixed will only show the fixed MOTD.
type="random"
random-motd=[
  "<red>random</red>",
  "<blue>random2</blue>",
]
fixed-motd="<yellow>fixed motd</yellow>"
# Set a custom favicon here. This allows you to reload the icon without having to reload the proxy/server.
# Place the icon in the hyperMOTD folder with the config.yml
use-custom-icon=false
custom-icon-filename="server-icon.png"