name: DMC-MOTD
main: lol.hyper.motdbukkit.MOTDBukkit
version: ${project.version}
author: hyperdefined
commands:
  motdreload:
    usage: /motdreload
    description: Reload the config.
libraries:
  - net.kyori:adventure-api:4.10.1
  - net.kyori:adventure-platform-bukkit:4.1.0
  - commons-io:commons-io:2.11.0