name: hyperMOTD
main: lol.hyper.hypermotd.MOTDPaper
version: ${project.version}
author: hyperdefined
folia-supported: true
commands:
  hypermotd:
    usage: /hypermotd
    description: Reload the config.