name: hyperMOTD
main: lol.hyper.hypermotd.MOTDPaper
version: ${project.version}
author: hyperdefined
folia-supported: true
api-version: 1.21
website: https://github.com/hyperdefined/hyperMOTD
commands:
  hypermotd:
    usage: /hypermotd
    description: Reload the config.
permissions:
  hypermotd.reload:
    description: Allows the usage of /hypermotd.
    default: op